
services:
  xmrig:
    image: ghcr.io/murf2/xmrig.docker:latest
    container_name: xmrig
    hostname: xmrig
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - THREADS=3
      - PRIORITY=1
      - POOL_URL=gulf.moneroocean.stream:10128
      - POOL_USER=4AizaNghM3D1AcaWM2fUmLDLyhFQvphyMEUB3aBn1Q2tiugHbofqgnuFBXvJ9M1d27b9DjoCZSBdcM7EpWBw2SS2FVMUNZr
      - POOL_PASS=zimaos_sensecap
